# Generated by Django 4.2.6 on 2023-11-09 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='produit')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='catalogue.categorie')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True)),
                ('date_fin', models.DateField(blank=True)),
                ('pourcentage_promo', models.PositiveIntegerField(default=0.0, null=True)),
                ('prix_promo', models.FloatField(blank=True, default=0.0)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='catalogue.produit')),
            ],
        ),
    ]
